// GENERATED by tools/gen-so100.mjs — do not edit. Same source of truth as
// catalog/parts/so100 + examples/so100/assembly.json: the SO-ARM100 URDF joint
// table (Apache-2.0). Y-up world, SI metres, wxyz quaternions, zero pose.
//   links[i]:  { name, p0, q0, bone }  — bone = child-joint origin in the
//              link's local frame (null for the leaf jaw)
//   joints[i]: { name, pivot0, axis0, min, max, vel, parent, child }
//   servos[i]: { p0, q0, joint, parent, mesh } — STS3215 bodies (case rides
//              parent; mesh = which servo glb variant this joint renders)
export const SO100 = {
  "links": [
    {
      "name": "base",
      "p0": [
        0,
        0,
        0
      ],
      "q0": [
        0.707106781,
        -0.707106781,
        0,
        0
      ],
      "bone": [
        0,
        -0.0452,
        0.0165
      ]
    },
    {
      "name": "shoulder",
      "p0": [
        0,
        0.0165,
        0.0452
      ],
      "q0": [
        1,
        -0.000003163,
        0,
        0
      ],
      "bone": [
        0,
        0.1025,
        0.0306
      ]
    },
    {
      "name": "upper_arm",
      "p0": [
        0,
        0.119000194,
        0.075799352
      ],
      "q0": [
        0.62160749,
        -0.783328876,
        0,
        0
      ],
      "bone": [
        0,
        0.11257,
        0.028
      ]
    },
    {
      "name": "lower_arm",
      "p0": [
        0,
        0.120691054,
        -0.040188346
      ],
      "q0": [
        0.99343967,
        -0.114357431,
        0,
        0
      ],
      "bone": [
        0,
        0.0052,
        0.1349
      ]
    },
    {
      "name": "wrist",
      "p0": [
        0,
        0.156406271,
        0.090001797
      ],
      "q0": [
        0.816999458,
        -0.576638436,
        0,
        0
      ],
      "bone": [
        0,
        -0.0601,
        0
      ]
    },
    {
      "name": "gripper",
      "p0": [
        0,
        0.1362742,
        0.146629614
      ],
      "q0": [
        0.577707684,
        -0.407746238,
        0.577704029,
        -0.407743659
      ],
      "bone": [
        -0.0202,
        -0.0244,
        0
      ]
    },
    {
      "name": "jaw",
      "p0": [
        -1.28e-7,
        0.147133757,
        0.176386463
      ],
      "q0": [
        -0.577700374,
        0.407741079,
        0.577711339,
        -0.407748818
      ],
      "bone": null
    }
  ],
  "joints": [
    {
      "name": "shoulder_pan",
      "pivot0": [
        0,
        0.0165,
        0.0452
      ],
      "axis0": [
        0,
        1,
        -0.000006327
      ],
      "min": -2,
      "max": 2,
      "vel": 1,
      "parent": 0,
      "child": 1
    },
    {
      "name": "shoulder_lift",
      "pivot0": [
        0,
        0.119000194,
        0.075799352
      ],
      "axis0": [
        1,
        0,
        0
      ],
      "min": 0,
      "max": 3.5,
      "vel": 1,
      "parent": 1,
      "child": 2
    },
    {
      "name": "elbow_flex",
      "pivot0": [
        0,
        0.120691054,
        -0.040188346
      ],
      "axis0": [
        1,
        0,
        0
      ],
      "min": -3.14158,
      "max": 0,
      "vel": 1,
      "parent": 2,
      "child": 3
    },
    {
      "name": "wrist_flex",
      "pivot0": [
        0,
        0.156406271,
        0.090001797
      ],
      "axis0": [
        1,
        0,
        0
      ],
      "min": -2.5,
      "max": 1.2,
      "vel": 1,
      "parent": 3,
      "child": 4
    },
    {
      "name": "wrist_roll",
      "pivot0": [
        0,
        0.1362742,
        0.146629614
      ],
      "axis0": [
        0,
        0.334976228,
        -0.942226579
      ],
      "min": -3.14158,
      "max": 3.14158,
      "vel": 1,
      "parent": 4,
      "child": 5
    },
    {
      "name": "gripper",
      "pivot0": [
        -1.28e-7,
        0.147133757,
        0.176386463
      ],
      "axis0": [
        -1,
        -0.000017884,
        -0.000006358
      ],
      "min": -0.2,
      "max": 2,
      "vel": 1,
      "parent": 5,
      "child": 6
    }
  ],
  "servos": [
    {
      "p0": [
        0,
        0.0165,
        0.0452
      ],
      "q0": [
        0.707104545,
        -0.707109018,
        0,
        0
      ],
      "joint": 0,
      "parent": 0,
      "mesh": "sts3215"
    },
    {
      "p0": [
        0.030000086,
        0.119000194,
        0.075799352
      ],
      "q0": [
        0.000002238,
        0.707106781,
        -0.000002238,
        -0.707106781
      ],
      "joint": 1,
      "parent": 1,
      "mesh": "sts3215"
    },
    {
      "p0": [
        0.030249146,
        0.120691054,
        -0.040188346
      ],
      "q0": [
        0.081661665,
        0.702375521,
        -0.081661665,
        -0.702375521
      ],
      "joint": 2,
      "parent": 2,
      "mesh": "sts3215"
    },
    {
      "p0": [
        0.030202672,
        0.156406271,
        0.090001797
      ],
      "q0": [
        0.439553165,
        -0.553888992,
        -0.439553165,
        0.553888992
      ],
      "joint": 3,
      "parent": 3,
      "mesh": "sts3215"
    },
    {
      "p0": [
        0,
        0.151232521,
        0.104554607
      ],
      "q0": [
        0.698920933,
        0.120543041,
        -0.119816884,
        0.694710601
      ],
      "joint": 4,
      "parent": 4,
      "mesh": "sts3215_wrist"
    },
    {
      "p0": [
        -0.029702967,
        0.147133226,
        0.176386274
      ],
      "q0": [
        0.120171958,
        -0.696820422,
        0.120158731,
        -0.696822703
      ],
      "joint": 5,
      "parent": 5,
      "mesh": "sts3215"
    }
  ]
};
